# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-12 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
                ('site_title', models.CharField(blank=True, max_length=200, null=True)),
                ('site_header', models.CharField(blank=True, max_length=200, null=True)),
                ('parsing_complete', models.BooleanField(default=False)),
                ('timeshift_for_parsing', models.PositiveIntegerField(default=0)),
                ('parsing_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': '\u0441\u0430\u0439\u0442 \u0434\u043b\u044f \u043f\u0430\u0440\u0441\u0438\u043d\u0433\u0430',
            },
        ),
    ]
