# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-12 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteadminmodel',
            name='parsing_time',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='siteadminmodel',
            name='site_header',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteadminmodel',
            name='site_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
