# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-12 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_parser', '0002_auto_20190712_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteadminmodel',
            name='parsing_time',
            field=models.DateTimeField(null=True),
        ),
    ]
