# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-31 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites_parser', '0004_auto_20190713_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteadminmodel',
            options={},
        ),
    ]
